name: Update README
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          readme_filepath: ./README.md
          FILTER_EVENTS: PullRequestEvent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
